<a href="https://colab.research.google.com/github/Maxwell6321/611-ds-project/blob/main/python-intro-hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework: Introduction to Python

## Problem 1: Containers and Functions

**(a)** Write a function called `unique_sorted` that takes a list of integers and returns a **new** list containing the unique values in ascending order. For example, `unique_sorted([3, 1, 2, 3, 2])` should return `[1, 2, 3]`.

In [21]:
def unique_sorted(values):
    unique_list = list(set(values))
    unique_list.sort()
    return unique_list

In [2]:
print(unique_sorted([3, 1, 2, 3, 2]))

[1, 2, 3]


**(b)** Write a function called `count_words` that takes a list of strings and returns a dictionary mapping each word (lowercased) to its count. For example, `count_words(["Apple", "banana", "apple", "BANANA"])` should return `{'apple': 2, 'banana': 2}`.

In [3]:
def count_words(words):
    counts = {}
    for word in words:
      lower_word = word.lower()
      if lower_word in counts:
        counts[lower_word] = counts[lower_word] + 1
      else:
          counts[lower_word] = 1
    return(counts)

In [4]:
print(count_words(["Apple", "banana", "apple", "BANANA"]))

{'apple': 2, 'banana': 2}


**(c)** You are given a list of `(name, score)` tuples. Write a function called `average_scores` that returns a dictionary mapping each name to their average score. If a name appears multiple times, you should average all of their scores. For example, `average_scores([("Ada", 90), ("Bob", 80), ("Ada", 100)])` should return `{'Ada': 95.0, 'Bob': 80.0}`.

In [5]:
def average_scores(records):
    total_scores = {}
    counts ={}
    for name, score in records:
        if name in total_scores:
            total_scores[name] =  total_scores[name] + score
            counts[name] = counts[name] + 1
        else:
              total_scores[name] = score
              counts[name] = 1
    averages = {}
    for name in total_scores:
        averages[name] = total_scores[name] / counts[name]
    return averages

In [6]:
print(average_scores([("Ada", 90), ("Bob", 80), ("Ada", 100)]))

{'Ada': 95.0, 'Bob': 80.0}


## Problem 2: Writing Functions with Comprehensions

**(a)** Write a function called `filter_by_threshold` that takes a list of numbers and a threshold value, and returns a new list containing only the numbers greater than the threshold. Use a list comprehension. For example, `filter_by_threshold([1, 5, 3, 8, 2], 3)` should return `[5, 8]`.

In [7]:
def filter_by_threshold(numbers, threshold):
  return [num for num in numbers if num > threshold]

In [8]:
print(filter_by_threshold([1, 5, 3, 8, 2], 3))

[5, 8]


**(b)** Write a function called `word_lengths` that takes a list of strings and returns a dictionary mapping each unique word to its length. Use a dictionary comprehension. For example, `word_lengths(["hello", "world", "hi"])` should return `{'hello': 5, 'world': 5, 'hi': 2}`.

In [9]:
def word_lengths(words):
  return {word: len(word) for word in words}

In [10]:
print(word_lengths(["hello", "world", "hi"]))

{'hello': 5, 'world': 5, 'hi': 2}


**(c)** Write a function called `common_elements` that takes two lists and returns a set of elements that appear in both lists. Use a set comprehension. For example, `common_elements([1, 2, 3, 4], [3, 4, 5, 6])` should return `{3, 4}`.

In [11]:
def common_elements(list1, list2):
    return {x for x in list1 if x in list2}

In [12]:
print(common_elements([1, 2, 3, 4], [3, 4, 5, 6]))

{3, 4}


## Problem 3: NumPy Array Operations

**(a)** Given the following 2D array, write NumPy code to:
1. Extract the second row as a 1D array
2. Extract the last column as a 2D column vector (shape should be `(4, 1)`)
3. Extract the 2x2 subarray from the bottom-right corner

In [25]:
import numpy as np

data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
second_row = data[1, :]
print("Second row:", second_row)

last_column = data[:, -1:]
print("Last column:\n", last_column)

bottom_right = data[2:, 2:]
print("Bottom-right 2x2:\n", bottom_right)

Second row: [5 6 7 8]
Last column:
 [[ 4]
 [ 8]
 [12]
 [16]]
Bottom-right 2x2:
 [[11 12]
 [15 16]]


**(b)** Without using loops, write NumPy code to:
1. Create a 5x5 array where each element is the sum of its row and column indices (i.e., element at position `[i, j]` should equal `i + j`)
2. Normalize each row of a matrix so that each row sums to 1 (use broadcasting)

In [14]:
# Given matrix for part 2
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], dtype=float)
cols = np.arange(5)
rows = np.arange(5).reshape(5, 1)
sum_grid = rows + cols
print("Sum Grid (i + j):\n", sum_grid)

row_sums = matrix.sum(axis=1, keepdims=True)
normalized_matrix = matrix / row_sums
print("\nNormalized Matrix:\n", normalized_matrix)

Sum Grid (i + j):
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]

Normalized Matrix:
 [[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]
 [0.29166667 0.33333333 0.375     ]]


**(c)** Explain the difference between the following two indexing operations. What are the shapes of `a` and `b`? Which one creates a view and which creates a copy?

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = arr[0:1, :]
b = arr[[0], :]

The shapes of a and b are the same: (1:3). a creates a view and b creates a copy.

## Problem 4: Improving Inefficient Code

The following code computes pairwise distances between points but is inefficient. Rewrite it using NumPy broadcasting to eliminate the nested loops. Your solution should produce the same result as the original code.

In [16]:
import numpy as np

def pairwise_distances_slow(points):
    """Compute pairwise Euclidean distances between points.

    Parameters
    ----------
    points : np.ndarray
        Array of shape (n, d) where n is number of points and d is dimensions.

    Returns
    -------
    np.ndarray
        Array of shape (n, n) containing pairwise distances.
    """
    n = points.shape[0]
    distances = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            diff = points[i] - points[j]
            distances[i, j] = np.sqrt(np.sum(diff ** 2))
    return distances



In [17]:
import numpy as np

def pairwise_distances_fast(points):
  points_expanded = points[:, np.newaxis, :]
  diff = points_expanded - points
  distances = np.sqrt(np.sum(diff ** 2, axis=-1))
  return distances

## Problem 5: The View Trap

A colleague wrote the following function to standardize columns of a matrix (subtract mean, divide by standard deviation). However, users are reporting unexpected behavior.

In [18]:
import numpy as np

def standardize_columns(data):
    """Standardize each column to have mean 0 and std 1."""
    result = data
    for j in range(data.shape[1]):
        col = result[:, j]
        col_mean = np.mean(col)
        col_std = np.std(col)
        col = (col - col_mean) / col_std
    return result

**(a)** Explain why this function does not work as intended. What fundamental concept about NumPy arrays is being misunderstood?

**(b)** A user runs the following code and is surprised by the output. Explain what happens and why.

**(a)** The fundamental concept being misunderstood is how Python handles names vs. memory. The specific error happens at: col = (col - col_mean) / col_std. Python creates a brand new array in a new memory location containing the standardized numbers and moves the label to point to this new array.

**(b)** The original and normalized object are the same, the math didn't happen. This was because the original column inside result was left behind, untouched. The function effectively calculated the answer, held it for one microsecond, and then threw it away when the loop moved to the next iteration.

In [19]:
original = np.array([[1.0, 2.0], [3.0, 4.0]])
normalized = standardize_columns(original)
print("Original:", original)
print("Normalized:", normalized)
print("Are they the same object?", original is normalized)

Original: [[1. 2.]
 [3. 4.]]
Normalized: [[1. 2.]
 [3. 4.]]
Are they the same object? True


**(c)** Rewrite the function correctly. Your solution should actually standardize the columns, not modify the input array, and use vectorized operations instead of explicit loops where possible.

**(d)** Write a simple test that verifies your corrected function works properly. The test should check that the output columns have approximately mean 0 and standard deviation 1.

In [20]:
import numpy as np

def standardize_columns(data):
    col_means = data.mean(axis=0)
    col_stds = data.std(axis=0)
    result = (data - col_means) / col_stds
    return result

original = np.array([[1.0, 2.0], [3.0, 4.0]])
normalized = standardize_columns(original)
print("Original:", original)
print("Normalized:", normalized)
print("Are they the same object?", original is normalized)

Original: [[1. 2.]
 [3. 4.]]
Normalized: [[-1. -1.]
 [ 1.  1.]]
Are they the same object? False
